version: "3"
services:
  api:
    image: node:20
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    working_dir: /app
    command: bash -c "npm install --legacy-peer-deps && npm run start"

  front:
    image: node:20
    ports:
      - "4000:3000"
    volumes:
      - ./front/:/app
      - /app/node_modules
    working_dir: /app
    command: bash -c "npm install && npm run start"
